logging:
  level:
    org.springframework: error
    org.springframework.security: error
    com.agiraud.charon: debug

server:
  port: 8090

spring:
  data:
    cassandra:
      keyspace-name: oauth
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists
  